version: "3.3"

services:
  db:
    image: postgres:11.5-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - db.env
    networks:
      db2app:
        aliases:
          - db

  app:
    image: nextcloud:17.0.1-fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - datastorage:/mnt/data-storage
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: nextcloud
      NEXTCLOUD_TRUSTED_DOMAINS: micro-world.xyz
      NEXTCLOUD_DATA_DIR: /mnt/data-storage/data
    env_file:
      - db.env
      - nextcloud.env
    depends_on:
      - db
    networks:
      db2app:
      proxy2app:
        aliases:
          - app

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs: #/etc/nginx/certs:ro
        type: bind
        source: /etc/nginx/certs
        target: /etc/nginx/certs:ro
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nextcloud:/var/www/html:ro
    depends_on:
      - app
    links:
      - app
    networks:
      - proxy2app

volumes:
  db:
  nextcloud:
  datastorage:
     external:
       name: cloud-storage
  html:

networks:
  db2app:
  proxy2app:
